# Generated by Django 3.2.11 on 2022-06-28 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_type_slug'),
        ('app_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicimage',
            name='Electronic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electronic_image', to='base.electronic'),
        ),
        migrations.AlterField(
            model_name='electronicimage',
            name='image',
            field=models.ImageField(upload_to='electronic/'),
        ),
    ]
