# Generated by Django 3.2.11 on 2022-06-28 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_type_slug'),
        ('app_image', '0002_auto_20220628_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingandbeautyimage',
            name='clothingandbeauty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothingandbeauty_image', to='base.clothingandbeauty'),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_image', to='base.job'),
        ),
        migrations.AlterField(
            model_name='petimage',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_image', to='base.pet'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_image', to='base.property'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_image', to='base.vehicle'),
        ),
    ]
