# Generated by Django 3.2.11 on 2022-07-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_image', '0003_auto_20220628_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electronicimage',
            old_name='Electronic',
            new_name='electronic',
        ),
    ]
