# Generated by Django 3.2.11 on 2022-06-03 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220602_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=600, null=True, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=500, null=True)),
                ('electronic_model', models.CharField(blank=True, max_length=500, null=True)),
                ('condition', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(blank=True, max_length=500, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=500, null=True)),
                ('expiry_date', models.DateTimeField(auto_now=True)),
                ('company_profile', models.TextField(blank=True, max_length=600, null=True)),
                ('job_description', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_age', models.CharField(blank=True, max_length=500, null=True)),
                ('cat_breed', models.CharField(blank=True, max_length=500, null=True)),
                ('dog_breed', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_type', models.CharField(blank=True, max_length=500, null=True)),
                ('colour', models.CharField(blank=True, max_length=500, null=True)),
                ('broker_fee', models.BooleanField(default=False)),
                ('plot_size', models.CharField(blank=True, max_length=200, null=True)),
                ('erf_size', models.CharField(blank=True, max_length=500, null=True)),
                ('furnishing', models.CharField(blank=True, max_length=500, null=True)),
                ('fenced', models.BooleanField(default=False)),
                ('property_address', models.CharField(blank=True, max_length=500, null=True)),
                ('parking_space', models.BooleanField(default=False)),
                ('security_available', models.CharField(blank=True, max_length=500, null=True)),
                ('bedroom', models.CharField(blank=True, max_length=500, null=True)),
                ('bathroom', models.CharField(blank=True, max_length=500, null=True)),
                ('kitchen', models.CharField(blank=True, max_length=500, null=True)),
                ('lounge', models.CharField(blank=True, max_length=500, null=True)),
                ('dining_room', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=500, null=True)),
                ('model', models.CharField(blank=True, max_length=500, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=500, null=True)),
                ('body_type', models.CharField(blank=True, max_length=500, null=True)),
                ('transmission', models.CharField(blank=True, max_length=500, null=True)),
                ('mileage', models.CharField(blank=True, max_length=500, null=True)),
                ('conditions', models.CharField(blank=True, max_length=500, null=True)),
                ('number_of_ownners', models.CharField(blank=True, max_length=500, null=True)),
                ('colour', models.CharField(blank=True, max_length=500, null=True)),
                ('property_type', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.region')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.subcategory')),
                ('postered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
