# Generated by Django 3.2.11 on 2022-06-03 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_electronics_job_pets_product_property_region_subcategory_subregion_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingAndBeauty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(blank=True, max_length=500, null=True)),
                ('age_group', models.CharField(blank=True, max_length=500, null=True)),
                ('skin_type', models.CharField(blank=True, max_length=500, null=True)),
                ('shoe_sizes', models.CharField(blank=True, max_length=500, null=True)),
                ('dress_sizes', models.CharField(blank=True, max_length=500, null=True)),
                ('general_sizes', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Electronics',
            new_name='Electronic',
        ),
        migrations.RenameModel(
            old_name='Pets',
            new_name='Pet',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.subcategory'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='postered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
