# Generated by Django 3.2.11 on 2022-06-04 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220603_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingandbeauty',
            old_name='dress_sizes',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='clothingandbeauty',
            name='shoe_sizes',
        ),
        migrations.RemoveField(
            model_name='electronic',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='job',
            name='working_hours',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='cat_breed',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='dog_breed',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='make',
        ),
        migrations.AlterField(
            model_name='property',
            name='seller_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='clothingandbeauty',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.type'),
        ),
        migrations.AddField(
            model_name='electronic',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.type'),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.type'),
        ),
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.type'),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.type'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.type'),
        ),
    ]
