# Generated by Django 3.2.11 on 2022-06-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220604_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingandbeauty',
            name='size',
        ),
        migrations.RemoveField(
            model_name='property',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='property_type',
        ),
        migrations.AddField(
            model_name='clothingandbeauty',
            name='dress_sizes',
            field=models.CharField(blank=True, choices=[('4(XS)', '4(XS)'), ('6(S)', '6(S)'), ('8(S)', '8(S)'), ('10(S/M)', '10(S/M)'), ('12(XS)', '12(XS)'), ('14(M)', '14(M)'), ('16(M)', '16(M)'), ('18(L/M)', '18(L/M)'), ('20(L)', '20(L)'), ('22(L)', '22(L)'), ('24(XL)', '24(XL)'), ('26(XL)', '26(XL)'), ('28(XL)(2XL)', '28(XL)(2XL)'), ('30(2XL)', '30(2XL)'), ('32(3XL)', '32(3XL)'), ('34(3XL)', '34(3XL)'), ('36(4XL)', '36(4XL)'), ('N/A', 'N/A'), ('Other', 'Other')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clothingandbeauty',
            name='shoe_sizes',
            field=models.CharField(blank=True, choices=[('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('5.5', '5.5'), ('6.0', '6.0'), ('6.5', '6.5'), ('7.0', '7.0'), ('7.5', '7.5'), ('8.0', '8.0'), ('8.5', '8.5'), ('9.0', '9.0'), ('9.5', '9.5'), ('10.0', '10.0'), ('10.5', '10.5'), ('11.0', '11.0'), ('11.5', '11.5'), ('12.0', '12.0'), ('12.5', '12.5'), ('13.0', '13.0'), ('13.5', '13.5'), ('14.0', '14.0'), ('14.5', '14.5'), ('15.0', '15.0'), ('Other', 'Other')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clothingandbeauty',
            name='age_group',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Children', 'Children'), ('Baby', 'Baby')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clothingandbeauty',
            name='gender',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Woman', 'Woman'), ('Unisex', 'Unisex')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clothingandbeauty',
            name='general_sizes',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('XXXXL', 'XXXXL'), ('N/A', 'N/A'), ('Other', 'Other')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clothingandbeauty',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Dry', 'Dry'), ('Oily', 'Oily'), ('Sensitive', 'Sensitive'), ('All', 'All')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('Furnished', 'Furnished'), ('UnFurnished', 'UnFurnished')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='seller_type',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Seller', 'Seller'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Bakkie', 'Bakkie'), ('Sports', 'Sports'), ('Other', 'Other')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='colour',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Grey', 'Grey'), ('Black', 'Black'), ('Silver', 'Silver'), ('Red', 'Red'), ('Blue', 'Blue')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='conditions',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Other', 'Other'), ('Electric', 'Electric'), ('Other', 'Other')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Other', 'Other')], max_length=500, null=True),
        ),
    ]
