# Generated by Django 3.2.11 on 2022-06-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220606_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='working_hours',
            field=models.CharField(blank=True, choices=[('Full_time', 'Full_time'), ('Part_time', 'Part_time')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='cat_breed',
            field=models.CharField(blank=True, choices=[('Rex', 'Rex'), ('Bengal', 'Bengal')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='dog_breed',
            field=models.CharField(blank=True, choices=[('Bulldog', 'Bulldog'), ('German Shepherd', 'German Shepherd')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Training', 'Training'), ('Volunteer', 'Volunteer'), ('Training', 'Training'), ('Other', 'Other')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_age',
            field=models.CharField(blank=True, choices=[('0-3 months', '0-3 months'), ('3-6 months', '3-6 months'), ('6-12 months', '6-12 months')], max_length=500, null=True),
        ),
    ]
