# Generated by Django 3.2.11 on 2022-07-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20220709_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingandbeauty',
            name='image_urls',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='electronic',
            name='image_urls',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='image_urls',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='image_urls',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='image_urls',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image_urls',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
